#
# Basic settings.
#
#url: http://qckanemoto.github.io # or http://you.github.io
lang: en
url: http://neontapir.github.io
baseurl: ""
title: Chuck Durfee
description: "The neon tapir, casting his eerie glow upon the masses"
avatar: /assets/img/tapir.png
show_drafts: false

#
# Defaults
#

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author:
        login: Chuck
        email: neontapir@gmail.com
        display_name: Chuck
        first_name: Chuck
        last_name: Durfee

#
# Icons
#
icons:
  rss: true
  email: neontapir@gmail.com
  github: neontapir
  bitbucket:
  twitter: ChuckDurfee
  facebook: chuck.durfee
  google_plus: +ChuckDurfee
  tumblr:
  behance:
  dribbble:
  flickr: tangentier
  instagram: neontapir
  linkedin: https://www.linkedin.com/in/neontapir # full URL
  pinterest:
  reddit: neontapir
  soundcloud:
  stack_exchange: http://stackexchange.com/users/19520/neontapir # full URL
  steam:
  wordpress: neontapir
  youtube: neontapir

#
# Prettify url.
#
permalink: pretty

#
# Scripts.
#
google_analytics: UA-67306270-1
disqus: neontapir-dot-com

#
# Localizations.
#
str_next: Next
str_prev: Prev
str_read_more: Read more...
str_search: Search
str_recent_posts: Recent posts
str_show_all_posts: Show all posts

#
# Recent posts.
#
recent_posts_num: 10

#
# Pagination.
#
paginate: 10
paginate_path: page/:num

#
# Social.
#
share_buttons: true
ogp:
  image_url: /assets/img/tapir.png
  fb:
    admin: # facebook admin id
    app_id: 710997945694360 # facebook application id

#
# Gems.
#
gems:
  - jekyll-sitemap
  - jemoji

#
# Styles: see "_sass/base/_variables.scss"
#

#
# !! Danger zone !!
#

include: ["_pages"]

markdown: redcarpet
redcarpet:
  extensions: ["autolink", "fenced_code_blocks", "strikethrough", "superscript", "with_toc_data", "tables", "footnotes", "no_intra_emphasis"]
highlighter: pygments

excerpt_separator: <!--more-->

sass:
  sass_dir: _sass
  style: :compressed # or :expanded

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - vendor
