#
# Basic settings.
#
# url: http://qckanemoto.github.io # or http://you.github.io
lang: en-US
url: http://neontapir.github.io
baseurl: ""
title: Chuck Durfee's Blog
description: The neon tapir, casting his eerie glow upon the masses
avatar: /assets/img/tapir-hex.png
show_drafts: false

# Additional Jekyll SEO tag information

author: chuckdurfee
facebook:
  app_id: 194566184373771
  publisher: 10153287725984334
  admins: 10153287725984334
logo: /assets/img/tapir-hex.png
social:
  name: Chuck Durfee
  links:
    - http://twitter.com/ChuckDurfee
    - https://www.linkedin.com/in/neontapir
    - https://github.com/neontapir
    - https://keybase.io/neontapir

#
# Defaults
#

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      logo: /assets/img/tapir-hex.png
      social:
        name: Chuck Durfee
      twitter:
        username: ChuckDurfee
      author:
        login: Chuck
        email: neontapir+blog@gmail.com
        display_name: Chuck
        first_name: Chuck
        last_name: Durfee
      read_stats:
        wpm: 160
#
# Icons via https://github.com/FortAwesome/Font-Awesome
#
icons:
  behance:
  bitbucket: 
  dribbble:
  email: neontapir+blog@gmail.com
  facebook: chuck.durfee
  # flickr: tangentier
  github: neontapir
  instagram: neontapir
  linkedin: agilechuckwagon
  patreon: agilechuckwagon
  pinterest:
  reddit: neontapir
  rss: true
  soundcloud:
  stack_exchange: 19520/neontapir
  steam:
  tumblr:
  twitter: ChuckDurfee
  # wordpress: neontapir
  youtube: neontapir

#
# Prettify url.
#
permalink: pretty

#
# Scripts.
#
google_analytics: UA-67306270-1
disqus: neontapir-dot-com

#
# Localizations.
#
str_next: Next
str_prev: Prev
str_read_more: Read more...
str_search: Search
str_recent_posts: Recent posts
str_show_all_posts: Show all posts

#
# Recent posts.
#
recent_posts_num: 10

#
# Pagination.
#
paginate: 5
paginate_path: page/:num

#
# Theme version
#
version: 2.1.0

#
# Social.
#
share_buttons:
  twitter: true
  facebook: true # needs ogp.fb.app_id
  hatena: false # styling has been removed
ogp:
  image_url: /assets/img/tapir-hex.png
  fb:
    admin: 10153287725984334 # facebook admin id
    app_id: 194566184373771 # facebook application id

#
# Gems, first default includes, then custom
#
plugins:
  - jekyll-coffeescript
  - jekyll-default-layout
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-readme-index
  - jekyll-titles-from-headings
  - jekyll-relative-links
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji
#   - octopress-minify-html

#
# Styles: see "_sass/base/_variables.scss"
#

#
# !! Danger zone !!
#

include: ["_pages"]

markdown: kramdown
highlighter: rouge

excerpt_separator: <!--more-->

sass:
  sass_dir: _sass
  style: :compressed # or :expanded

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - NOTES.md
  - Rakefile.rb
  - README.md
  - vendor

theme: jekyll-theme-cayman
# theme: jekyll-theme-dinky

# search will not normally work locally because of CORS
# uncomment the follow to bypass this for debugging

# webrick:
#   headers:
#     Access-Control-Allow-Origin: '*'