source "https://rubygems.org"

gem 'jekyll', '3.0.3'
gem 'kramdown', '1.10.0'
gem 'rdiscount', '2.1.8'
gem 'RedCloth', '4.2.9'
gem 'liquid', '3.0.6'
gem 'rouge', '1.10.1'
gem 'github-pages'
gem 'github-pages-health-check', '1.1.0'
gem 'celluloid', '0.16.0'
gem 'timers', '4.0.4'
gem 'nokogiri'
gem 'classifier-reborn'
#gem 'closure-compiler'

group :jekyll_plugins do
  #gem 'jekyll-coffeescript'
  gem 'jekyll-feed'
  #gem 'jekyll-gist'
  #gem 'jekyll-github-metadata'
  #gem 'jekyll-mentions'
  gem 'jekyll-paginate'
  #gem 'jekyll-redirect-from'
  #gem 'jekyll-sass-converter'
  gem 'jekyll-seo-tag'
  gem 'jekyll-sitemap'
  #gem 'jekyll-textile-converter'
  gem 'jemoji'
  #gem 'octopress-minify-html'
end
