source "https://rubygems.org"

gem 'jekyll', '3.0.3'
gem 'jekyll-sass-converter', '1.3.0'
gem 'jekyll-textile-converter', '0.1.0'
gem 'kramdown', '1.10.0'
gem 'rdiscount', '2.1.8'
gem 'RedCloth', '4.2.9'
gem 'liquid', '3.0.6'
gem 'rouge', '1.10.1'
gem 'github-pages'
gem 'github-pages-health-check', '1.1.0'
gem 'jemoji', '0.6.2'
gem 'jekyll-mentions', '1.1.2'
gem 'jekyll-redirect-from', '0.10.0'
gem 'jekyll-sitemap', '0.10.0'
gem 'jekyll-feed', '0.4.0'
gem 'jekyll-gist', '1.4.0'
gem 'jekyll-paginate', '1.1.0'
gem 'jekyll-coffeescript', '1.0.1'
gem 'jekyll-seo-tag', '1.3.3'
gem 'jekyll-github-metadata', '1.10.0'
gem 'celluloid', '0.16.0'
gem 'timers', '4.0.4'
gem 'nokogiri'
gem 'classifier-reborn'
