source "https://rubygems.org"

gem 'jekyll', '>=3.6.2'
# gem 'RedCloth', '4.2.9'
# gem 'celluloid', '0.16.0'
# gem 'classifier-reborn', '2.1.0'
# gem 'github-pages', '>=167'
# gem 'github-pages-health-check', '1.1.0'
# gem 'jekyll-coffeescript', '1.0.1'
gem 'jekyll-feed' #, '0.4.0'
# gem 'jekyll-gist', '1.4.0'
# gem 'jekyll-github-metadata', '1.10.0'
# gem 'jekyll-mentions', '1.1.2'
gem 'jekyll-paginate' #, '1.1.0'
# gem 'jekyll-redirect-from', '0.10.0'
# gem 'jekyll-sass-converter', '1.5.0'
gem 'jekyll-seo-tag' #, '1.3.3'
gem 'jekyll-sitemap' #, '0.10.0'
# gem 'jekyll-textile-converter', '0.1.0'
gem 'jemoji' #, '0.8.0'
gem 'kramdown', '>=1.14'
gem 'liquid', '>=4.0'
# gem 'nokogiri', '1.8.0'
gem 'pkg-config', '~>1.1'
# gem 'rdiscount', '2.1.8'
# gem 'redcarpet', '3.3.3'
gem 'rouge', '>=2.2.1'
# gem 'timers', '4.0.4'
